import type { NextPage, GetStaticProps, GetStaticPaths } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

import Layout from "~/c/Layout";
import Article from "~/c/Article";

import { unified } from "unified";
import remarkParse from "remark-parse";
import remarkRehype from "remark-rehype";

import { GET } from "~/lib/api";

import Node from "~/t/Node";

interface Props {
  node: Node;
}

const NodePage: NextPage<Props> = ({ node }) => {
  return (
    <Layout>
      <Head>
        <title>{node.name}</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.main}>
        <Article markdown={node.content} />
      </main>
    </Layout>
  );
};

export const getStaticProps: GetStaticProps = async (context) => {
  const slug = context?.params?.slug;
  const node = await GET(`public/node/${slug}`);

  return {
    props: { node }, // will be passed to the page component as props
  };
};

export const getStaticPaths: GetStaticPaths = async () => {
  const slugs = await GET(`public/index`);
  console.log(slugs);
  return {
    paths: slugs.map((slug: string) => {
      return { params: { slug } };
    }),
    // TODO: setup a fallback page
    fallback: false,
  };
};

export default NodePage;
