import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

import { unified } from "unified";
import remarkParse from "remark-parse";
import remarkRehype from "remark-rehype";
import rehypeStringify from "rehype-stringify";

const Home: NextPage = ({ node }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>{node.name}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main
        className={styles.main}
        dangerouslySetInnerHTML={{ __html: node.content }}
      ></main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export async function getStaticProps(context) {
  const slug = context.params.slug;

  const res = await fetch(`http://localhost:8000/public/node/${slug}`, {
    headers: { Authorization: "wMHDXuKaYJ3wnYmrpnOKmgtt" },
  });
  const node = await res.json();
  const content = unified()
    .use(remarkParse)
    .use(remarkRehype)
    .use(rehypeStringify)
    .processSync(node.content).value;

  console.log({ node: { ...node, content } });

  return {
    props: { node: { ...node, content } }, // will be passed to the page component as props
  };
}

export async function getStaticPaths() {
  const res = await fetch(`http://localhost:8000/public/index`, {
    headers: { Authorization: "wMHDXuKaYJ3wnYmrpnOKmgtt" },
  });
  const slugs = await res.json();
  console.log(slugs);
  return {
    paths: slugs.map((slug) => {
      return { params: { slug } };
    }),
    fallback: true,
  };
}

export default Home;
