import type { NextPage, GetStaticProps } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

import Layout from "~/c/Layout";
import Article from "~/c/Article";

import { unified } from "unified";
import remarkParse from "remark-parse";
import remarkRehype from "remark-rehype";

import { GET } from "~/lib/api";

import Node from "~/t/Node";

interface Props {
  node: Node;
}

const Home: NextPage<Props> = ({ node }) => {
  return (
    <Layout>
      <Head>
        <title>{node.name}</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.main}>
        <Article markdown={node.content} />
      </main>
    </Layout>
  );
};

export const getStaticProps: GetStaticProps = async (context) => {
  const node = await GET(`public/root`);

  return {
    props: { node }, // will be passed to the page component as props
  };
};

export default Home;
